const API_URL = process.env.REACT_APP_API_URL;
const API_KEY = process.env.REACT_APP_API_KEY;

const MAX_NUMBER_RESULT = 10;
const MAX_NUMBER_OF_IMAGES = 100;
const MAX_NUMBER_OF_NEWS = 20;

export { API_URL, API_KEY, MAX_NUMBER_RESULT, MAX_NUMBER_OF_IMAGES, MAX_NUMBER_OF_NEWS };
